<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>An Analysis of Glassdoor Data Analyst Listings</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 45px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h2 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h3 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h4 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h5 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h6 {
  padding-top: 50px;
  margin-top: -50px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HOME</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="glassdoor_analysis.html">Glassdoor Analysis</a>
</li>
<li>
  <a href="Heart_disease.html">Cleveland Heart Disease Project</a>
</li>
<li>
  <a href="ins_regression.html">Predicting Medical Expense</a>
</li>
<li>
  <a href="scouting_a_team.html">Scouting an Athletics Team</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">An Analysis of Glassdoor Data Analyst Listings</h1>

</div>


<p> </p>
<div id="using-data-cleaning-ggplot-and-dplyr-to-analyze-numerically-and-visually-data-analyst-positions-by-location-industry-and-salary-as-well-as-performing-text-and-sentiment-analysis-on-the-job-descriptions." class="section level3">
<h3>Using data cleaning, ggplot and dplyr to analyze numerically and visually data analyst positions by location, industry, and salary as well as performing text and sentiment analysis on the job descriptions.</h3>
<p> </p>
<p>This projects data was collected using webscraping from Glassdoor to compile data analyst positions listed across the united states.</p>
<p>I am interested in finding out:</p>
<ul>
<li>The distribution of salaries for data analyst positions</li>
<li>What different industries are hiring data analysts?</li>
<li>What these industries offer data analysts in salaries?</li>
<li>Where are most of these positions located for analyst positions, by their respective industry?</li>
</ul>
<p> </p>
</div>
<div id="summary-of-findings-from-this-analysis" class="section level3">
<h3><strong>Summary of findings from this analysis</strong></h3>
<ul>
<li><p>New York is the city with the most jobs in the most industries that are hiring right now.</p></li>
<li><p>Biotech is the industry which pays the most on average out of the top 20 industries with the most postings, while News pays the most overall on average.</p></li>
<li><p>The top industries hiring include IT, Staffing, Health Care, Computer Hardware, Consulting and many more.</p></li>
<li><p>A pessimistic estimate of the range of salaries for data analysts are between $29,000 -$112,000.</p></li>
<li><p>SQL is the most common language that data analyst positions use in this data, with Excel and Python falling behind it. A small number of positions mention using all three.</p></li>
<li><p>Job descriptions overall are worded slightly positive, but are fairly neutral. It is rare you’ll find any position that sounds too positive or negative overall.</p></li>
</ul>
<p> </p>
</div>
<div id="loading-in-and-cleaning-the-data" class="section level3">
<h3><strong>1. Loading in and cleaning the data</strong></h3>
<p>I’ll take a look at the data using the glimpse() function, since head() may not print nicely because of long text strings in the fields.</p>
<pre><code>## New names:
## * `` -&gt; ...1</code></pre>
<pre><code>## Observations: 2,253
## Variables: 16
## $ ...1                &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ...
## $ `Job Title`         &lt;chr&gt; &quot;Data Analyst, Center on Immigration and J...
## $ `Salary Estimate`   &lt;chr&gt; &quot;$37K-$66K (Glassdoor est.)&quot;, &quot;$37K-$66K (...
## $ `Job Description`   &lt;chr&gt; &quot;Are you eager to roll up your sleeves and...
## $ Rating              &lt;dbl&gt; 3.2, 3.8, 3.4, 4.1, 3.9, 3.9, 4.4, 3.7, 4....
## $ `Company Name`      &lt;chr&gt; &quot;Vera Institute of Justice\r\n3.2&quot;, &quot;Visit...
## $ Location            &lt;chr&gt; &quot;New York, NY&quot;, &quot;New York, NY&quot;, &quot;New York,...
## $ Headquarters        &lt;chr&gt; &quot;New York, NY&quot;, &quot;New York, NY&quot;, &quot;New York,...
## $ Size                &lt;chr&gt; &quot;201 to 500 employees&quot;, &quot;10000+ employees&quot;...
## $ Founded             &lt;dbl&gt; 1961, 1893, 2003, 2002, 2009, 2014, 2001, ...
## $ `Type of ownership` &lt;chr&gt; &quot;Nonprofit Organization&quot;, &quot;Nonprofit Organ...
## $ Industry            &lt;chr&gt; &quot;Social Assistance&quot;, &quot;Health Care Services...
## $ Sector              &lt;chr&gt; &quot;Non-Profit&quot;, &quot;Health Care&quot;, &quot;Information ...
## $ Revenue             &lt;chr&gt; &quot;$100 to $500 million (USD)&quot;, &quot;$2 to $5 bi...
## $ Competitors         &lt;chr&gt; &quot;-1&quot;, &quot;-1&quot;, &quot;GoDaddy&quot;, &quot;-1&quot;, &quot;DraftKings&quot;,...
## $ `Easy Apply`        &lt;dbl&gt; 1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -...</code></pre>
<p> </p>
<p>Definitely will have some data cleaning to do with this. I’m going to:</p>
<ul>
<li>remove extra text from salary column</li>
<li>remove the rating that shouldn’t be in the company name column</li>
<li>remove rows where salary = ""</li>
<li>make salary and rating a numeric data type for analysis</li>
</ul>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Job Title
</th>
<th style="text-align:right;">
Salary
</th>
<th style="text-align:right;">
Rating
</th>
<th style="text-align:left;">
Comp_name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Data Analyst
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:left;">
Vera Institute of
</td>
</tr>
<tr>
<td style="text-align:left;">
Quality Data Analyst
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
3.8
</td>
<td style="text-align:left;">
Visiting Nurse Service of New
</td>
</tr>
<tr>
<td style="text-align:left;">
Senior Data Analyst
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
3.4
</td>
<td style="text-align:left;">
Squarespace
</td>
</tr>
<tr>
<td style="text-align:left;">
Data Analyst
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:left;">
Celerity
</td>
</tr>
<tr>
<td style="text-align:left;">
Reporting Data Analyst
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:left;">
FanDuel
</td>
</tr>
<tr>
<td style="text-align:left;">
Data Analyst
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:left;">
Point72
</td>
</tr>
</tbody>
</table>
<p>I chose to keep the smallest value in the estimated salary range, so our data may look like salaries are on the low side.</p>
<p> </p>
</div>
<div id="visualizing-distribution-of-salaries" class="section level3">
<h3><strong>2. Visualizing distribution of salaries</strong></h3>
<p>I’ll create a histogram and print summary statistics to see what the salary range is</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   24.00   41.00   50.00   54.27   64.00  113.00</code></pre>
<p><img src="glassdoor_analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p> </p>
</div>
<div id="what-industries-are-looking-for-analysts" class="section level3">
<h3><strong>3. What industries are looking for Analysts?</strong></h3>
I’ll see which industries have more analyst position postings right now. I’ll view the top 20 industries.
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
325
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing &amp; Outsourcing
</td>
<td style="text-align:right;">
322
</td>
</tr>
<tr>
<td style="text-align:left;">
Health Care Services &amp; Hospitals
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:left;">
Computer Hardware &amp; Software
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
Consulting
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
Investment Banking &amp; Asset Management
</td>
<td style="text-align:right;">
78
</td>
</tr>
<tr>
<td style="text-align:left;">
Enterprise Software &amp; Network Solutions
</td>
<td style="text-align:right;">
69
</td>
</tr>
<tr>
<td style="text-align:left;">
Internet
</td>
<td style="text-align:right;">
65
</td>
</tr>
<tr>
<td style="text-align:left;">
Advertising &amp; Marketing
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Banks &amp; Credit Unions
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Insurance Carriers
</td>
<td style="text-align:right;">
47
</td>
</tr>
<tr>
<td style="text-align:left;">
Colleges &amp; Universities
</td>
<td style="text-align:right;">
40
</td>
</tr>
<tr>
<td style="text-align:left;">
Accounting
</td>
<td style="text-align:right;">
39
</td>
</tr>
<tr>
<td style="text-align:left;">
Biotech &amp; Pharmaceuticals
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
Social Assistance
</td>
<td style="text-align:right;">
23
</td>
</tr>
<tr>
<td style="text-align:left;">
Aerospace &amp; Defense
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
Video Games
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
Lending
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
State &amp; Regional Agencies
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
Architectural &amp; Engineering Services
</td>
<td style="text-align:right;">
13
</td>
</tr>
</tbody>
</table>
<p> </p>
Now I’ll shorten the text in the industry column to just keep the first word and create a plot to visualize the results of industries with 40 or more job postings.
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:right;">
325
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:right;">
322
</td>
</tr>
<tr>
<td style="text-align:left;">
Health
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:left;">
Computer
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
Consulting
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
Investment
</td>
<td style="text-align:right;">
78
</td>
</tr>
<tr>
<td style="text-align:left;">
Enterprise
</td>
<td style="text-align:right;">
69
</td>
</tr>
<tr>
<td style="text-align:left;">
Internet
</td>
<td style="text-align:right;">
65
</td>
</tr>
<tr>
<td style="text-align:left;">
Advertising
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Banks
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Insurance
</td>
<td style="text-align:right;">
47
</td>
</tr>
<tr>
<td style="text-align:left;">
Colleges
</td>
<td style="text-align:right;">
40
</td>
</tr>
</tbody>
</table>
<p><img src="glassdoor_analysis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p> </p>
</div>
<div id="what-do-data-anlysts-get-paid-in-different-industries" class="section level3">
<h3><strong>4. What do data anlysts get paid in different industries?</strong></h3>
<p>Let’s see how much data analysts get paid on average based on what industry they work in.</p>
I’ll use the top 20 industries by amount of jobs postings on Glassdoor to determine this.
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:right;">
325
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:right;">
322
</td>
</tr>
<tr>
<td style="text-align:left;">
Health
</td>
<td style="text-align:right;">
172
</td>
</tr>
<tr>
<td style="text-align:left;">
Computer
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
Consulting
</td>
<td style="text-align:right;">
111
</td>
</tr>
<tr>
<td style="text-align:left;">
Investment
</td>
<td style="text-align:right;">
78
</td>
</tr>
<tr>
<td style="text-align:left;">
Enterprise
</td>
<td style="text-align:right;">
69
</td>
</tr>
<tr>
<td style="text-align:left;">
Internet
</td>
<td style="text-align:right;">
65
</td>
</tr>
<tr>
<td style="text-align:left;">
Advertising
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Banks
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Insurance
</td>
<td style="text-align:right;">
51
</td>
</tr>
<tr>
<td style="text-align:left;">
Colleges
</td>
<td style="text-align:right;">
40
</td>
</tr>
<tr>
<td style="text-align:left;">
Accounting
</td>
<td style="text-align:right;">
39
</td>
</tr>
<tr>
<td style="text-align:left;">
Biotech
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
Social
</td>
<td style="text-align:right;">
23
</td>
</tr>
<tr>
<td style="text-align:left;">
Aerospace
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
Video
</td>
<td style="text-align:right;">
20
</td>
</tr>
<tr>
<td style="text-align:left;">
Lending
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
State
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
Architectural
</td>
<td style="text-align:right;">
13
</td>
</tr>
</tbody>
</table>
These are what industries pay data analysts the most on average
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
avg_sal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
News
</td>
<td style="text-align:right;">
84.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Drug
</td>
<td style="text-align:right;">
82.50
</td>
</tr>
<tr>
<td style="text-align:left;">
Education
</td>
<td style="text-align:right;">
69.67
</td>
</tr>
<tr>
<td style="text-align:left;">
Sports
</td>
<td style="text-align:right;">
69.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Utilities
</td>
<td style="text-align:right;">
67.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Miscellaneous
</td>
<td style="text-align:right;">
66.50
</td>
</tr>
<tr>
<td style="text-align:left;">
Chemical
</td>
<td style="text-align:right;">
65.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Gambling
</td>
<td style="text-align:right;">
64.00
</td>
</tr>
<tr>
<td style="text-align:left;">
Venture
</td>
<td style="text-align:right;">
62.83
</td>
</tr>
<tr>
<td style="text-align:left;">
Biotech
</td>
<td style="text-align:right;">
61.36
</td>
</tr>
<tr>
<td style="text-align:left;">
Electrical
</td>
<td style="text-align:right;">
60.83
</td>
</tr>
<tr>
<td style="text-align:left;">
Transportation
</td>
<td style="text-align:right;">
59.57
</td>
</tr>
<tr>
<td style="text-align:left;">
Cable
</td>
<td style="text-align:right;">
59.40
</td>
</tr>
<tr>
<td style="text-align:left;">
Accounting
</td>
<td style="text-align:right;">
59.15
</td>
</tr>
<tr>
<td style="text-align:left;">
Internet
</td>
<td style="text-align:right;">
58.43
</td>
</tr>
</tbody>
</table>
<p><img src="glassdoor_analysis_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Now. let’s see how much the industries with the most amount of jobs posted pay data analysts. <img src="glassdoor_analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p> </p>
</div>
<div id="what-location-has-the-most-jobs-for-each-industry" class="section level3">
<h3><strong>5. What location has the most jobs for each industry?</strong></h3>
<p>Now I’ll investigate to find out what industry in what cities have the most amount of job postings. My guess would be that New York would have the most positions and the most industries that are currently hiring.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:left;">
Location
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
46
</td>
</tr>
<tr>
<td style="text-align:left;">
Health
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
36
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
27
</td>
</tr>
<tr>
<td style="text-align:left;">
Investment
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
23
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:left;">
Charlotte
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
Charlotte
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
San Francisco
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
San Jose
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;">
Consulting
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
17
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:left;">
Chicago
</td>
<td style="text-align:right;">
17
</td>
</tr>
<tr>
<td style="text-align:left;">
Advertising
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
Internet
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
Internet
</td>
<td style="text-align:left;">
San Francisco
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
Denver
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:left;">
San Francisco
</td>
<td style="text-align:right;">
14
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
Chicago
</td>
<td style="text-align:right;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:left;">
Houston
</td>
<td style="text-align:right;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
IT
</td>
<td style="text-align:left;">
San Antonio
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:left;">
Staffing
</td>
<td style="text-align:left;">
Denver
</td>
<td style="text-align:right;">
12
</td>
</tr>
<tr>
<td style="text-align:left;">
State
</td>
<td style="text-align:left;">
Austin
</td>
<td style="text-align:right;">
12
</td>
</tr>
</tbody>
</table>
<p> </p>
<p>New York appears to have the most postings. To make this list easier to comprehend, I’ll plot number of positions per industry and facet wrap by city. <img src="glassdoor_analysis_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p> </p>
</div>
<div id="text-analysis" class="section level3">
<h3><strong>6. Text Analysis</strong></h3>
<p>I’m going to use the job description column for this data to perform a text analysis to view trends such as what words are used the most often in job descriptions and what programming languages appear the most often.</p>
<p><strong>Creating a corpus</strong></p>
<p>This first thing I’ll do is create a corpus, which is a way of storing data to be used for textual analysis.</p>
<pre class="r"><code>clean_data &lt;- data_4
corpus &lt;- SimpleCorpus(VectorSource(clean_data$`Job Description`))</code></pre>
<p><strong>Cleaning the corpus</strong></p>
<p>To clean the corpus to make text analysis simpler I’ll make 4 changes to it.</p>
<ul>
<li>Remove extra white space</li>
<li>Transform all words to lower case</li>
<li>Remove Punctuation</li>
<li>Removing stop words</li>
</ul>
<p>Stop words are common words of little value in text analysis, like “me, these, being,” etc. They appear often and don’t really provide any additional value. Here’s the fill list of stop words.</p>
<pre><code>##   [1] &quot;i&quot;          &quot;me&quot;         &quot;my&quot;         &quot;myself&quot;     &quot;we&quot;        
##   [6] &quot;our&quot;        &quot;ours&quot;       &quot;ourselves&quot;  &quot;you&quot;        &quot;your&quot;      
##  [11] &quot;yours&quot;      &quot;yourself&quot;   &quot;yourselves&quot; &quot;he&quot;         &quot;him&quot;       
##  [16] &quot;his&quot;        &quot;himself&quot;    &quot;she&quot;        &quot;her&quot;        &quot;hers&quot;      
##  [21] &quot;herself&quot;    &quot;it&quot;         &quot;its&quot;        &quot;itself&quot;     &quot;they&quot;      
##  [26] &quot;them&quot;       &quot;their&quot;      &quot;theirs&quot;     &quot;themselves&quot; &quot;what&quot;      
##  [31] &quot;which&quot;      &quot;who&quot;        &quot;whom&quot;       &quot;this&quot;       &quot;that&quot;      
##  [36] &quot;these&quot;      &quot;those&quot;      &quot;am&quot;         &quot;is&quot;         &quot;are&quot;       
##  [41] &quot;was&quot;        &quot;were&quot;       &quot;be&quot;         &quot;been&quot;       &quot;being&quot;     
##  [46] &quot;have&quot;       &quot;has&quot;        &quot;had&quot;        &quot;having&quot;     &quot;do&quot;        
##  [51] &quot;does&quot;       &quot;did&quot;        &quot;doing&quot;      &quot;would&quot;      &quot;should&quot;    
##  [56] &quot;could&quot;      &quot;ought&quot;      &quot;i&#39;m&quot;        &quot;you&#39;re&quot;     &quot;he&#39;s&quot;      
##  [61] &quot;she&#39;s&quot;      &quot;it&#39;s&quot;       &quot;we&#39;re&quot;      &quot;they&#39;re&quot;    &quot;i&#39;ve&quot;      
##  [66] &quot;you&#39;ve&quot;     &quot;we&#39;ve&quot;      &quot;they&#39;ve&quot;    &quot;i&#39;d&quot;        &quot;you&#39;d&quot;     
##  [71] &quot;he&#39;d&quot;       &quot;she&#39;d&quot;      &quot;we&#39;d&quot;       &quot;they&#39;d&quot;     &quot;i&#39;ll&quot;      
##  [76] &quot;you&#39;ll&quot;     &quot;he&#39;ll&quot;      &quot;she&#39;ll&quot;     &quot;we&#39;ll&quot;      &quot;they&#39;ll&quot;   
##  [81] &quot;isn&#39;t&quot;      &quot;aren&#39;t&quot;     &quot;wasn&#39;t&quot;     &quot;weren&#39;t&quot;    &quot;hasn&#39;t&quot;    
##  [86] &quot;haven&#39;t&quot;    &quot;hadn&#39;t&quot;     &quot;doesn&#39;t&quot;    &quot;don&#39;t&quot;      &quot;didn&#39;t&quot;    
##  [91] &quot;won&#39;t&quot;      &quot;wouldn&#39;t&quot;   &quot;shan&#39;t&quot;     &quot;shouldn&#39;t&quot;  &quot;can&#39;t&quot;     
##  [96] &quot;cannot&quot;     &quot;couldn&#39;t&quot;   &quot;mustn&#39;t&quot;    &quot;let&#39;s&quot;      &quot;that&#39;s&quot;    
## [101] &quot;who&#39;s&quot;      &quot;what&#39;s&quot;     &quot;here&#39;s&quot;     &quot;there&#39;s&quot;    &quot;when&#39;s&quot;    
## [106] &quot;where&#39;s&quot;    &quot;why&#39;s&quot;      &quot;how&#39;s&quot;      &quot;a&quot;          &quot;an&quot;        
## [111] &quot;the&quot;        &quot;and&quot;        &quot;but&quot;        &quot;if&quot;         &quot;or&quot;        
## [116] &quot;because&quot;    &quot;as&quot;         &quot;until&quot;      &quot;while&quot;      &quot;of&quot;        
## [121] &quot;at&quot;         &quot;by&quot;         &quot;for&quot;        &quot;with&quot;       &quot;about&quot;     
## [126] &quot;against&quot;    &quot;between&quot;    &quot;into&quot;       &quot;through&quot;    &quot;during&quot;    
## [131] &quot;before&quot;     &quot;after&quot;      &quot;above&quot;      &quot;below&quot;      &quot;to&quot;        
## [136] &quot;from&quot;       &quot;up&quot;         &quot;down&quot;       &quot;in&quot;         &quot;out&quot;       
## [141] &quot;on&quot;         &quot;off&quot;        &quot;over&quot;       &quot;under&quot;      &quot;again&quot;     
## [146] &quot;further&quot;    &quot;then&quot;       &quot;once&quot;       &quot;here&quot;       &quot;there&quot;     
## [151] &quot;when&quot;       &quot;where&quot;      &quot;why&quot;        &quot;how&quot;        &quot;all&quot;       
## [156] &quot;any&quot;        &quot;both&quot;       &quot;each&quot;       &quot;few&quot;        &quot;more&quot;      
## [161] &quot;most&quot;       &quot;other&quot;      &quot;some&quot;       &quot;such&quot;       &quot;no&quot;        
## [166] &quot;nor&quot;        &quot;not&quot;        &quot;only&quot;       &quot;own&quot;        &quot;same&quot;      
## [171] &quot;so&quot;         &quot;than&quot;       &quot;too&quot;        &quot;very&quot;</code></pre>
<pre class="r"><code># 1. strip white space
dfCorpus &lt;- tm_map(corpus, stripWhitespace)
# 2. Transforming everything to lowercase
dfCorpus &lt;- tm_map(dfCorpus, content_transformer(tolower))
# 3. Removing punctuation
dfCorpus &lt;- tm_map(dfCorpus, removePunctuation)
# 4. Removing stop words
dfCorpus &lt;- tm_map(dfCorpus, removeWords, stopwords(&quot;english&quot;))</code></pre>
<p>Here’s what the new job descriptions look similar towards after these changes</p>
<pre class="r"><code>dfCorpus[[10]]$content</code></pre>
<pre><code>## [1] &quot; us riskified   ai platform powering  ecommerce revolution  use cuttingedge technology machinelearning algorithms  behavioral analytics  identify legitimate customers  keep  moving toward checkout merchants use riskified  increase revenue prevent fraud  eliminate customer friction riskified  reviewed hundreds  millions  transactions  approved billions  dollars  revenue  merchants across virtually  industries including  number  fortune 500 companies   role   looking   data analyst  work directly   customers   merchant health team  will  part   growing operations team   responsible  riskifieds customers performance quick problemsolving  online fraud prevention  real time  will take  major part  research  investigation  new onlinefraud trends   superdynamic environment  therefore stand   forefront  riskifieds work youll  leveraging  analytical  data analysis skills  knowledge   product  provide meaningful insights   enterprise merchants including direct interaction  customers  youll   research  explore data using high level analytical tools r  sql   high level technical environment share deep analysis conclusions  sophisticated technical methods   clear manner   technical  nontechnical audiences work  account managers meet directly  clients  deliver analytic insights  business questions define  execute endtoend technical solutions  fraudprevention problems cooperate  various teams within riskified  enhance processes  meet customers needs master  online fraud prevention domain  handson analysis  live data qualifications candidates must  eligible  work   us without  visa sponsorship including opts 2 years  relevant strong analytical experience  complex data 12 years  handson work experience  sql 12 years  handson work experience  r  python experienced problem solver  critical thinker great written  verbal communication skills ability  work simultaneously  different tasks  lead multiple projects  position requires occasional evening  weekend shifts schedule  flexible   support  global client base life  riskified    fastgrowing  dynamic startup  450 team members   offices  tel aviv  new york city  value collaboration  innovative thinking  looking  bright driven  passionate people  grow  us  nyc benefits  perks fullycovered medical dental  vision insurance   first day stock options   employees 401k  matching commuter benefits catered lunch team events healthy snacks yoga pilates soccer league     news fortune magazine 25 best workplaces  new york announcing riskifieds 165m funding round inc magazine best workplaces built  nyc 100 best workplaces great place  work riskified crains best places  work  new york city techcrunch riskified prevents fraud   favorite ecommerce site riskified  deeply committed   principle  equal opportunity   individuals    discriminate based  race color religion sex sexual orientation national origin age disability veteran status    status protected  law&quot;</code></pre>
<p><strong>Creating a Document-Term Matrix to look for specific and most frequently occurring words</strong></p>
<p>A document-term matrix is a simple way to compare all the terms or words across each document. Viewing the data simply as a matrix results in each row representing a unique document and each column representing a unique term.</p>
<pre><code>## &lt;&lt;DocumentTermMatrix (documents: 2252, terms: 26182)&gt;&gt;
## Non-/sparse entries: 460338/58501526
## Sparsity           : 99%
## Maximal term length: 648
## Weighting          : term frequency (tf)
## Sample             :
##       Terms
## Docs   analysis analyst business data experience management skills team
##   1211        6       4        4   22         10         22     17    1
##   1413        1       2       16   11          6          8      3    8
##   2185       11       1        1   20         14          7      1    2
##   2204       16       1        2   27         19          9      2    2
##   375         1       3       13   22          5          8      2    7
##   567         1       0        5    3         11          4      3    3
##   582         3       6       11   17         16          6      6    0
##   676         4       1        9   29          8          8     16    3
##   76          3       0        5   28          6         10      1    5
##   893         7       1        1   43         24          4      7    0
##       Terms
## Docs   will work
##   1211    1    3
##   1413   14   12
##   2185   17    2
##   2204   21    4
##   375     0    6
##   567    24   18
##   582    14    4
##   676     0    7
##   76      5    5
##   893     0    3</code></pre>
<p>We can see we have a total of 26182 terms used throughout the 2252 job descriptions in the data set. Now I’m going to search for the names of specific languages to determine what languages are most common for data analyst jobs in this data.</p>
<p>Note: R and Rstudio are not found in this method due to some type of syntax error, even after making the conversions to the corpus I made before.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Count of Language Names
</caption>
<thead>
<tr>
<th style="text-align:left;">
docs
</th>
<th style="text-align:right;">
python
</th>
<th style="text-align:right;">
sql
</th>
<th style="text-align:right;">
excel
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
6
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>Python, SQL and Excel all have a presence in these job descriptions. Now to see how many times they are each mentioned in and what descriptions mention all 3.</p>
<pre class="r"><code># Number of descriptions that mention python
nrow(words_dtm_py)</code></pre>
<pre><code>## [1] 598</code></pre>
<pre class="r"><code># Number of descriptions that mention sql
nrow(words_dtm_sql)</code></pre>
<pre><code>## [1] 1318</code></pre>
<pre class="r"><code>#Number of descriptions that mention excel
nrow(words_dtm_xl)</code></pre>
<pre><code>## [1] 889</code></pre>
<pre class="r"><code>#Number of descriptions that mention all 3 languages
nrow(words_dtm_all)</code></pre>
<pre><code>## [1] 190</code></pre>
<p><img src="glassdoor_analysis_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Good thing I’ve been brushing up on using SQL becasue it is the most common language mentioned in job descriptions, so we can assume it is the most popular language requested to have some knowledge of or that the position would use in this dataset.</p>
<p><strong>Creating a word cloud of the most frequently appearing terms</strong></p>
<p>Word Clouds can be interesting and different ways to view the words the appear most often. Here I’ll visualize the 75 most common words, after removing stop words that otherwise would clutter the list.</p>
<pre class="r"><code>#creating word cloud of most frequent terms
sums &lt;- as.data.frame(colSums(as.matrix(DTM)))
sums &lt;- rownames_to_column(sums) 
colnames(sums) &lt;- c(&quot;term&quot;, &quot;count&quot;)
sums &lt;- arrange(sums, desc(count))
subs_sums &lt;- sums
subs_sums &lt;- as.data.table(subs_sums)

head &lt;- subs_sums[1:75,]
head &lt;- as.data.frame(head)</code></pre>
<pre class="r"><code>wordcloud(words = head$term, freq = head$count, min.freq = 1000,
          max.words=100, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, &quot;Dark2&quot;))</code></pre>
<p><img src="glassdoor_analysis_files/figure-html/unnamed-chunk-23-1.png" width="672" />  </p>
</div>
<div id="sentiment-analysis" class="section level3">
<h3><strong>7. Sentiment Analysis</strong></h3>
<p>Sentiments are opinions or feelings about something. So, I’ll use a sentiment analysis to capture the general feeling or tone which these job descriptions are written in. I’ll view which companies and industries have the most positively and negatively written job descriptions.</p>
<p>The type of sentiment analysis I will run uses the Harvard IV dictionary to detect how many negative and positive words are contained in text data. It grades the overall, positive and negative sentiment on a scale from -1 to 1.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Sentiment Analysis Polarity
</caption>
<thead>
<tr>
<th style="text-align:right;">
WordCount
</th>
<th style="text-align:right;">
SentimentGI
</th>
<th style="text-align:right;">
NegativityGI
</th>
<th style="text-align:right;">
PositivityGI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
654
</td>
<td style="text-align:right;">
0.0519878
</td>
<td style="text-align:right;">
0.0152905
</td>
<td style="text-align:right;">
0.0672783
</td>
</tr>
<tr>
<td style="text-align:right;">
433
</td>
<td style="text-align:right;">
0.0461894
</td>
<td style="text-align:right;">
0.0092379
</td>
<td style="text-align:right;">
0.0554273
</td>
</tr>
<tr>
<td style="text-align:right;">
433
</td>
<td style="text-align:right;">
0.1039261
</td>
<td style="text-align:right;">
0.0115473
</td>
<td style="text-align:right;">
0.1154734
</td>
</tr>
<tr>
<td style="text-align:right;">
498
</td>
<td style="text-align:right;">
0.0502008
</td>
<td style="text-align:right;">
0.0200803
</td>
<td style="text-align:right;">
0.0702811
</td>
</tr>
<tr>
<td style="text-align:right;">
334
</td>
<td style="text-align:right;">
0.0748503
</td>
<td style="text-align:right;">
0.0209581
</td>
<td style="text-align:right;">
0.0958084
</td>
</tr>
<tr>
<td style="text-align:right;">
253
</td>
<td style="text-align:right;">
0.0592885
</td>
<td style="text-align:right;">
0.0079051
</td>
<td style="text-align:right;">
0.0671937
</td>
</tr>
</tbody>
</table>
<p>Now I’ll view the overall distribution of sentiments in this data</p>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## -0.09091  0.03224  0.04699  0.04749  0.06272  0.15385</code></pre>
<p><img src="glassdoor_analysis_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>We can see the sentiment appears to be in the shape of a normal distribution and is centered to be slightly more positive than a neutral sentiment of zero.</p>
<p><strong>Viewing the most positive and negative job postings</strong></p>
<p>I wanted to see what companies and what industries have the most polarizing job descriptions in terms of sentiment. First I need to bind the columns from my sentiments analysis to the rest of the data, then I can analyze them.</p>
<p>Here are the companies with the highest and lowest sentiments in their job descriptions.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Highest Sentiment Companies
</caption>
<thead>
<tr>
<th style="text-align:left;">
Comp_name
</th>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
sent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
LeadStack,
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
0.1538462
</td>
</tr>
<tr>
<td style="text-align:left;">
LeadStack
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
0.1455696
</td>
</tr>
<tr>
<td style="text-align:left;">
TE
</td>
<td style="text-align:left;">
Electrical &amp; Electronic Manufacturing
</td>
<td style="text-align:right;">
0.1428571
</td>
</tr>
<tr>
<td style="text-align:left;">
O’Reilly
</td>
<td style="text-align:left;">
Automotive Parts &amp; Accessories Stores
</td>
<td style="text-align:right;">
0.1358025
</td>
</tr>
<tr>
<td style="text-align:left;">
CVS
</td>
<td style="text-align:left;">
Health Care Services &amp; Hospitals
</td>
<td style="text-align:right;">
0.1234568
</td>
</tr>
<tr>
<td style="text-align:left;">
Telligen
</td>
<td style="text-align:left;">
Health Care Services &amp; Hospitals
</td>
<td style="text-align:right;">
0.1225383
</td>
</tr>
<tr>
<td style="text-align:left;">
HR
</td>
<td style="text-align:left;">
Computer Hardware &amp; Software
</td>
<td style="text-align:right;">
0.1194030
</td>
</tr>
<tr>
<td style="text-align:left;">
Health &amp; Hospital
</td>
<td style="text-align:left;">
Health Care Services &amp; Hospitals
</td>
<td style="text-align:right;">
0.1192661
</td>
</tr>
<tr>
<td style="text-align:left;">
The Jupiter
</td>
<td style="text-align:left;">
Staffing &amp; Outsourcing
</td>
<td style="text-align:right;">
0.1167883
</td>
</tr>
<tr>
<td style="text-align:left;">
Beacon Hill Staffing
</td>
<td style="text-align:left;">
Staffing &amp; Outsourcing
</td>
<td style="text-align:right;">
0.1164659
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Lowest Sentiment Companies
</caption>
<thead>
<tr>
<th style="text-align:left;">
Comp_name
</th>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
sent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Advent Global Solutions,
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
-0.0602410
</td>
</tr>
<tr>
<td style="text-align:left;">
iSpace,
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
-0.0588235
</td>
</tr>
<tr>
<td style="text-align:left;">
Tecolote
</td>
<td style="text-align:left;">
Aerospace &amp; Defense
</td>
<td style="text-align:right;">
-0.0354610
</td>
</tr>
<tr>
<td style="text-align:left;">
Pareto
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
-0.0266667
</td>
</tr>
<tr>
<td style="text-align:left;">
Sharpedge Solutions
</td>
<td style="text-align:left;">
Publishing
</td>
<td style="text-align:right;">
-0.0227273
</td>
</tr>
<tr>
<td style="text-align:left;">
DATA
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
-0.0195503
</td>
</tr>
<tr>
<td style="text-align:left;">
SACC
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
-0.0121951
</td>
</tr>
<tr>
<td style="text-align:left;">
silverXis
</td>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
-0.0096154
</td>
</tr>
<tr>
<td style="text-align:left;">
UTHealth
</td>
<td style="text-align:left;">
Colleges &amp; Universities
</td>
<td style="text-align:right;">
-0.0042918
</td>
</tr>
<tr>
<td style="text-align:left;">
JPMorgan Chase &amp;
</td>
<td style="text-align:left;">
Investment Banking &amp; Asset Management
</td>
<td style="text-align:right;">
-0.0033445
</td>
</tr>
</tbody>
</table>
<p>Now the industries with the highest and lowest sentiment.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Highest Sentiment Industries
</caption>
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
sent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Security Services
</td>
<td style="text-align:right;">
0.0948867
</td>
</tr>
<tr>
<td style="text-align:left;">
News Outlet
</td>
<td style="text-align:right;">
0.0913043
</td>
</tr>
<tr>
<td style="text-align:left;">
Legal
</td>
<td style="text-align:right;">
0.0822848
</td>
</tr>
<tr>
<td style="text-align:left;">
Audiovisual
</td>
<td style="text-align:right;">
0.0775623
</td>
</tr>
<tr>
<td style="text-align:left;">
Hotels, Motels, &amp; Resorts
</td>
<td style="text-align:right;">
0.0716724
</td>
</tr>
<tr>
<td style="text-align:left;">
Preschool &amp; Child Care
</td>
<td style="text-align:right;">
0.0707745
</td>
</tr>
<tr>
<td style="text-align:left;">
Electrical &amp; Electronic Manufacturing
</td>
<td style="text-align:right;">
0.0681120
</td>
</tr>
<tr>
<td style="text-align:left;">
Food &amp; Beverage Stores
</td>
<td style="text-align:right;">
0.0662352
</td>
</tr>
<tr>
<td style="text-align:left;">
Transportation Management
</td>
<td style="text-align:right;">
0.0636109
</td>
</tr>
<tr>
<td style="text-align:left;">
Grocery Stores &amp; Supermarkets
</td>
<td style="text-align:right;">
0.0611021
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Lowest Sentiment Companies
</caption>
<thead>
<tr>
<th style="text-align:left;">
Industry
</th>
<th style="text-align:right;">
sent
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
General Merchandise &amp; Superstores
</td>
<td style="text-align:right;">
0.0270218
</td>
</tr>
<tr>
<td style="text-align:left;">
Health Fundraising Organizations
</td>
<td style="text-align:right;">
0.0277996
</td>
</tr>
<tr>
<td style="text-align:left;">
Building &amp; Personnel Services
</td>
<td style="text-align:right;">
0.0306373
</td>
</tr>
<tr>
<td style="text-align:left;">
Oil &amp; Gas Services
</td>
<td style="text-align:right;">
0.0314501
</td>
</tr>
<tr>
<td style="text-align:left;">
Education Training Services
</td>
<td style="text-align:right;">
0.0332469
</td>
</tr>
<tr>
<td style="text-align:left;">
IT Services
</td>
<td style="text-align:right;">
0.0344016
</td>
</tr>
<tr>
<td style="text-align:left;">
Metals Brokers
</td>
<td style="text-align:right;">
0.0347594
</td>
</tr>
<tr>
<td style="text-align:left;">
Pet &amp; Pet Supplies Stores
</td>
<td style="text-align:right;">
0.0355450
</td>
</tr>
<tr>
<td style="text-align:left;">
Publishing
</td>
<td style="text-align:right;">
0.0359135
</td>
</tr>
<tr>
<td style="text-align:left;">
Sporting Goods Stores
</td>
<td style="text-align:right;">
0.0367893
</td>
</tr>
</tbody>
</table>
<p>Sentiments appear pretty neutral in general. I suppose it is intuitive that you’re not going to find anything too joyful or dark in a data-analyst job description.</p>
<p> </p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
