---
title: "Data Analyst/Science Portfolio by Paul McGee"
output:
  html_document:
    fig_width: 1
---

----

My name is Paul McGee and I am a recent MBA graduate from Binghamton University with a concentration in Business Analytics. I graduated in 2019 from SUNY New Paltz with a Bachelor of Science in Marketing. This site is a compilation of independent projects which I have completed relating to data analysis and data science.

&nbsp;  

The tabs at the top of the page can be used to navigate between the projects I currently have posted. Each project involves some overlap of skills, but uses different analytical tools or methods to ultimately complete the task.


**Glassdoor Analysis** -  Using data cleaning, ggplot and dplyr to analyze numerically and visually data analyst positions by location, industry, and salary as well as performing text and sentiment analysis on the job descriptions. 

**Cleveland Heart Disease Project** - Using exploratory data analysis, tidyverse, ggplot, and multiple logistic regression to determine risk factors for heart disease.

**Predicting Medical Expenses** - Using linear regression, exploratory data analysis and data visualization to predict the amount which individuals have spent on health care.

**Scouting an Athletics Team** - Using the dplyr package, data cleaning, functions and more to draft and compete a team in a javelin event.

&nbsp;  

My email: pmcgee1@binghamton.edu

LinkedIn: https://www.linkedin.com/in/paul-mcgee-51187b130/

Copy of my Resume: https://github.com/Pmcgee57/Resume/raw/master/github%20resume.pdf 
